name: Chatrich
version: '1.0.10'
summary: Communicate with people in a meaningful way
base: core22
license: MIT
parts:
  library:
    plugin: maven
    source: https://github.com/frossm/library.git
    source-type: git
    source-tag: 'v2023.12.03'
    maven-parameters:
      - install

    build-packages:
      - maven
      - openjdk-17-jdk-headless
confinement: devmode
description: |
