name: Distribute Android Artifact

on:
  # Reusable workflows (other workflows can trigger this)
  workflow_call:
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Prepare access to everything
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Decode Local properties
        run: echo "${{ secrets.LOCAL_PROPERTIES }}" | base64 --decode > /Users/runner/work/Communication-enrichment/Communication-enrichment/local.properties
      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > /Users/runner/work/keystore.jks
      - name: Decode google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES }}" | base64 --decode > /Users/runner/work/Communication-enrichment/Communication-enrichment/composeApp/google-services.json

      # Prepare the environment
      - name: Build with Gradle and Print Version
        id: gradle
        run: |
          VERSION=$(./gradlew -q printVersionName)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

        # Android - create a bundle
      - name: Build Android Release
        run: ./gradlew bundleRelease
      - name: Export Android .aab to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: ${{ github.workspace }}/composeApp/build/outputs/bundle/release/composeApp-release.aab

      - name: Increase version code
        run: awk '/version-code/ {gsub(/[0-9]+/, ++n)} {print}' n=$(awk -F'"' '/version-code/ {print $2}' gradle/libs.versions.toml) gradle/libs.versions.toml > temp && mv temp gradle/libs.versions.toml

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'git@github.com'
          git checkout -b release-${{ env.VERSION }}
          git add gradle/libs.versions.toml
          git commit -m 'Increment version code'
          git push origin release-${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request to master
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Automatic release of version ${{ env.VERSION }}'
          branch: release-${{ env.VERSION }}
          base: master
          title: 'Release ${{ env.VERSION }}'
          body: 'Automatic release of version ${{ env.VERSION }}'

      # Android - upload the bundle to Google Play Console
      - name: Publish Android to Play Store internal test track
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          packageName: chat.enrichment.eu
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          releaseFiles: ${{ github.workspace }}/composeApp/build/outputs/bundle/release/composeApp-release.aab
          track: internal
          status: draft
          inAppUpdatePriority: 3