name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Decode Keystore properties
      run: echo "${{ secrets.KEYSTORE_PROPERTIES }}" | base64 --decode > /home/runner/work/Communication-enrichment/Communication-enrichment/keystore.properties
    - name: Decode Keystore
      run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > /tmp/keystore.jks
    - name: Decode google-services.json
      run: echo "${{ secrets.GOOGLE_SERVICES }}" | base64 --decode > /home/runner/work/Communication-enrichment/Communication-enrichment/composeApp/google-services.json
    - name: Build Jvm
      run:
        export DISPLAY=:99
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
        ./gradlew run
    - name: Build Android Release
      run: ./gradlew assembleRelease
