name: Distribute Artifacts

on:
  workflow_run:
    workflows: [ "Build and extract Master" ]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Android - upload the bundle to Firebase distribution
      - name: Firebase App Distribution initialization
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0

      - name: Download Android artifact
        uses: actions/download-artifact@master
        with:
          name: android-release
          path: ${{ github.workspace }}/composeApp/build/outputs/bundle/release/composeApp-release.aab
      - name: Display structure of downloaded files
        run: ls -R

      - name: Upload Android to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.ANDROID_RELEASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_DISTRIBUTION_CREDENTIALS_CONTENT }}
          groups: internal-testing
          file: ${{ github.workspace }}/composeApp-release.aab