name: Build and extract Master

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # Prepare access to everything
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Decode Local properties
      run: echo "${{ secrets.LOCAL_PROPERTIES }}" | base64 --decode > /Users/runner/work/Communication-enrichment/Communication-enrichment/local.properties
    - name: Decode Keystore
      run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > /Users/runner/work/keystore.jks
    - name: Decode google-services.json
      run: echo "${{ secrets.GOOGLE_SERVICES }}" | base64 --decode > /Users/runner/work/Communication-enrichment/Communication-enrichment/composeApp/google-services.json

    # Prepare the environment
    - name: Build with Gradle and Print Version
      id: gradle
      run: |
        VERSION=$(./gradlew -q printVersionName)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    # Build the app and export the output files

    # Android
    - name: Build Android Release
      run: ./gradlew bundleRelease
    - name: Export Android .aab to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Android ${{ env.VERSION }}
        path: /Users/runner/work/Communication-enrichment/Communication-enrichment/composeApp/build/outputs/bundle/release/composeApp-release.aab

    # iOS - Dmg
    - name: Build iOS Release
      run: ./gradlew packageReleaseDmg
    - name: Export iOS .dmg to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: iOS ${{ env.VERSION }}
        path: /Users/runner/work/Communication-enrichment/Communication-enrichment/composeApp/build/compose/binaries/main-release/dmg/Chatrich-${{ env.VERSION }}.dmg

      # Windows - Msi
    - name: Build Windows Release
      run: ./gradlew packageReleaseMsi
    - name: Export Windows .msi to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Windows ${{ env.VERSION }}
        path: /Users/runner/work/Communication-enrichment/Communication-enrichment/composeApp/build/compose/binaries/main-release/app/Chatrich

      # Linux - Deb
    - name: Build Linux Release
      run: ./gradlew packageReleaseDeb