name: Build and extract Master

on:
  push:
    branches: [ "master" ]

jobs:
  compile:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      # We need Java to build Android and Jvm
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      # Saves up some space
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
          cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}

  deploy-windows:
    uses: ./.github/workflows/windows-distribution.yml
    needs: compile

  deploy-linux:
    uses: ./.github/workflows/linux-distribution.yml
    needs: deploy-windows

  deploy-android:
    uses: ./.github/workflows/android-distribution.yml
    needs: deploy-linux

  deploy-ios:
    uses: ./.github/workflows/ios-distribution.yml
    needs: deploy-linux