name: Build and extract Master

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # Prepare access to everything
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Decode Local properties
      run: echo "${{ secrets.LOCAL_PROPERTIES }}" | base64 --decode > /Users/runner/work/Communication-enrichment/Communication-enrichment/local.properties
    - name: Decode Keystore
      run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > /Users/runner/work/keystore.jks
    - name: Decode google-services.json
      run: echo "${{ secrets.GOOGLE_SERVICES }}" | base64 --decode > /Users/runner/work/Communication-enrichment/Communication-enrichment/composeApp/google-services.json

    # Prepare the environment
    - name: Build with Gradle and Print Version
      id: gradle
      run: |
        ./gradlew printVersionName > version.txt
        VERSION=$(tail -n 1 version.txt)
        echo "VERSION=$VERSION" >> $GITHUB_ENV


    # Build the app and export the output files

    # Android
    - name: Build Android Release
      run: ./gradlew assembleRelease
    - name: Export Android APK to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Android ${{ env.VERSION }}
        path: /Users/runner/work/Communication-enrichment/Communication-enrichment/composeApp/build/outputs/apk/release/composeApp-release.apk

    # iOS
    - name: Build iOS
      run: ./gradlew packageDmg

    # Jvm
    - name: Build Jvm
      run: ./gradlew packageMsi
