name: Distribute Linux artifact

on:
  # Reusable workflows (other workflows can trigger this)
  workflow_call:
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Prepare access to everything
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Decode Local properties
        run: | 
          echo "${{ secrets.LOCAL_PROPERTIES }}" | base64 --decode > ${{ github.workspace }}/local.properties
          awk '{if ($1 == "storeFile=") print "storeFile=${{ github.workspace }}/keystore.jks"; else print $0}' ${{ github.workspace }}/local.properties > temp && mv temp ${{ github.workspace }}/local.properties
      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > ${{ github.workspace }}/keystore.jks
      - name: Decode google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES }}" | base64 --decode > ${{ github.workspace }}/composeApp/google-services.json

      # Linux - Deb
      - name: Build Linux Release
        run: ./gradlew packageReleaseDeb

      - name: Move and rename DEB file
        run: |
          mkdir -p downloads/${{ env.VERSION }}
          mv ${{ github.workspace }}/composeApp/build/compose/binaries/main-release/deb/chatrich_${{ env.VERSION }}-1_amd64.deb ${{ github.workspace }}/Chatrich.deb

      - name: Upload DEB file to FTP
        run: |
          curl ftp://${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}@${{ secrets.FTP_SERVER_DOMAIN }}/downloads/www/${{ env.VERSION }}/ --ftp-create-dirs
          curl -T ${{ github.workspace }}/Chatrich.deb ftp://${{ secrets.FTP_SERVER_DOMAIN }}/downloads/www/${{ env.VERSION }}/ --user ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}
